language: ruby
cache: bundler
dist: trusty
sudo: false

env:
  - VAULT_VERSION=0.9.6
  - VAULT_VERSION=0.8.3
  - VAULT_VERSION=0.7.3
  - VAULT_VERSION=0.6.5
  - VAULT_VERSION=0.5.3
  - VAULT_VERSION=0.4.1
  - VAULT_VERSION=0.3.1

gemfile:
  - Gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

before_install:
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir -p ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

matrix:
  exclude:
    # Rails 4.1 cannot build json gem dependency any longer with Ruby 2.4
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails_4.2.gemfile

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
  - bundle exec rake app:db:test:prepare
