language: ruby
cache: bundler
dist: trusty
sudo: false

gemfile:
  - Gemfile
  - gemfiles/rails_4.2.gemfile

before_install:
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir -p ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

matrix:
  exclude:
    # Json 1.8.3 cannot build json gem dependency any longer with Ruby 2.4
    - rvm: 2.4.4
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails_4.2.gemfile

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
  - bundle exec rake app:db:test:prepare
